### ISSUE TITLE
不调用dealloc方法

### ISSUE THREAD

**Issue by AidyBao** [1273011249/XYYSegmentControl#1]
按照你的方法创建后,不调用dealloc呀,我试做修改,但没有成功,帮忙再看看,等待回复

邮箱：281907061@qq.com

**Comment by ubsion** [comment]
你好，很感谢支持使用XYYSegmentControl，感谢你的提问。我这边给一个办法先解决问题：

self.slideSwitchView = [[XYYSegmentControl alloc]initWithFrame:CGRectMake(0 , 64 , self.view.frame.size.width, self.view.frame.size.height - 64) channelName:_itemArray source:nil];
创建的时候source设为nil。
这个bug是因为控制器互相引用了，今天下班之后我会更新下代码。:-D

**Comment by AidyBao** [comment]
感谢你在百忙中回复我的问题

按照你的办法虽然能解决内存泄漏的问题,但有新的问题,就是屏幕失去点击事件了，你再研究一下,我也看看，如果有解决办法了，请帮忙更新一下,谢谢！

邮箱：281907061@qq.com

**Comment by ubsion** [comment]
感谢提出问题，谢谢对XYYSegmentControl支持。已经更新代码，问题我已经通过邮件回答了。稍后会跟新pod,fix无法dealloc、无法愉快捕获点击事件问题

**Comment by AidyBao** [comment]
Good,

所有问题都已得到解决
再次感谢,“星星”是必须的
