### ISSUE TITLE
关于rightItem的问题

### ISSUE THREAD

**Issue by shmily1119** [1273011249/XYYSegmentControl#3]
在不同的viewcontroller里面，点击右上角的筛选，出现不同的内容，这个怎么去判断？

**Comment by ubsion** [comment]
前一阵忙着过年没看到，不好意思哈。

- (void)slideSwitchView:(XYYSegmentControl *)view didselectTab:(NSUInteger)number

实现这个代理，当点击进入相应的tab的时候，会调用它。希望能帮到你，要是还不能满足需求再来进行更进。
